name: Hello Actions

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v3

      - name: Afficher un message
        run: echo "GitHub Actions fonctionne !"
